my_list=[]
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
print(my_list)
my_list.insert(1,15)
another_list=[50,60,70]
my_list.extend(another_list)
print(my_list)
my_list.pop()
print(my_list)
my_list.sort()
print(my_list)
index_30=my_list.index(30)
print("Index of the value 30 is",index_30)
